export enum TermFormKeys {
  NAME = "name",
  AGE = "age",
  GENDER = "gender",
  HEALTH_CONDITION = "any_health_condition",
  SMOKING = "smoking_condition",
  ALCOHOLIC = "alcoholic_condition",
  NOMINES = "no_nomines",
  PROFESSION = "profession",
  LPA = "LPA",
  CLAIM_AMT = "claim_amount",
  PREMIUM_AMT = "premium_amount",
  SUB_TYPE = "subscription_type",
  POLICY_DURATION = "policy_duration",
}

export enum LiabilityFormKeys {
  NAME = "name",
  ADDRESS = "address",
  LOCATION_TYPE = "location_type",
  MOBILE = "mobile",
  BUSINESS_TYPE = "business_type",
  BUSINESS_DESC = "business_desc",
  SERVICES = "services",
  TARGET = "target",
  CLAIM_HISTORY = "claim_history",
  CLAIM_TYPE = "claim_type",
  CLAIM_AMT = "claim_amt",
  RISK_ASS = "risk_ass",
  RESPONSE_PLAN = "response_plan",
  BUILDING_AGE = "building_age",
  CONSTRUCTION_MTRL = "construction_mtrl",
  PROTECTION = "protection",
  CONTROL_MEASURES = "control_measures",
  BUILDING_TYPE = "building_type",
  POLICY_TYPE = "policy_type",
  POLICY_PERIOD = "policy_period",
  LIMIT = "limit",
  PROPERTY = "property",
  PROPERTY_VALUE = "property_value",
  LIABILITY_EXPOSURE = "liability_exposure",
  REVENUE = "revenue",
  ENV_CONCERN = "env_concern",
  REGULATORY_ISSUE = "regulatory_issues",
  SPECIFIC_RISK = "specific_risk",
}

export enum DisabilityFormKeys {
  NAME = "name",
  ADDRESS = "address",
  DOB = "dob",
  AGE = "age",
  SECURITY_NUM = "security_num",
  JOB_TITLE = "job_title",
  COMPANY = "company",
  INDUSTRY = "industry",
  DURATION = "duration",
  JOB_DUTIES = "job_duties",
  ANNUAL_INCOME = "annual_income",
  EDUCATION = "education",
  CLG = "clg",
  PAST_ILLNESS = "past_illness",
  INJURIES = "injuries",
  CURRENT_HEALTH_STATUS = "current_health_status",
  FAM_ILLNESS_HISTORY = "family_illness_history",
  CURRENT_TREATMENT = "current_treatment",
  DISABILITY_INFO = "disability_info",
  DISABILITY_DURATION = "disability_duration",
  DAILY_IMPACT = "daily_impact",
  DOCTOR_NAME = "doctor_name",
  DOCTOR_ADDRESS = "doctor_address",
  DOCTOR_CONTACT_INFO = "doctor_contact_info",
  SERVICE_PERIOD = "service_period",
  INCOME = "income",
  OTHER_INCOME = "other_source_of_income",
  DEPENDENTS = "dependents",
  SPOUSE_NAME = "spouse_name",
  SPOUSE_AGE ="spouse_age",
  CHILDREN_CNT = "children_count",
  CHILDREN_NAME_AGE = "children_name_and_age",
  MILITARY_SERVICE_DATE = "military_service_date",
  LIFE_INSURANCE = "life_insurance",
  HEALTH_INSURANCE = "health_insurance",
  LONG_TERM_CARE_INSURANCE = "long_term_care_insurance"
}

export enum AutomobileFormKeys {
  NAME = "name",
  ADDRESS = "address",
  DOB = "dob",
  GENDER = "gender",
  PHONE = "phone",
  EMAIL = "email",
  VEHICLE_MAKE = "vehicle_make",
  VEHICLE_MODEL = "vehicle_model",
  VEHICLE_YEAR = "vehicle_year",
  VIN = "VIN",
  VEHICLE_CLASS = "vehicle_classification",
  ENGINE_CAPACITY = "engine_capacity",
  FUEL_TYPE = "fuel_type",
  VEHICLE_VALUE = "vehicle_value",
  DRIVER_LICENSE_NUM = "Driver_license_num",
  DRIVER_LINCENSE_CLASS = "Driver_license_class",
  DRIVING_EXPERIENCE = "Driving_experience",
  PREVIOUS_VIOLATION = "previous_violation",
  INSURANCE_TYPE = "insurance_type",
  POLICY_START = "policy_start_date",
  POLICY_END = "policy_end_date",
  COVERAGE_LIMIT = "coverage_limit",
  DEDUCTIBLE_AMT = "deductible_amount",
  PREMIUM_AMT = "premium_amount",
  PAYMENT_FREQ = "payment_frequency",
  PAYMENT_METHOD = "payment_method",
  ADDITIONAL_DRIVER = "additional_driver",
  ADDITIONAL_FEATURE = "additional_features"
}

export enum PetFormKeys {
  FULL_NAME = "full_name",
  ADDRESS = "address",
  CITY = "city",
  STATE = "state",
  ZIP_CODE = "zip_code",
  PHONE_NO = "phone_number",
  EMAIL = "email_address",
  PET_NAME = "pet_name",
  SPECIES = "species",
  BREED = "breed",
  AGE = "age",
  GENDER = "gender",
  SPAYED_NEUTERED = "spayed_neutered",
  MICROCHIPPED = "microchipped",
  MICROCHIP_NO = "microchip_number",
  ACCIDENT_COVERAGE = "accident_coverage",
  ILLNESS_COVERAGE = "illness_coverage",
  ROUTINE_CARE = "routine_care",
  OTHER = "other",
  MEDICAL_CONDITION = "medical_conditions",
  PREV_INJURIES_ILLNESS = "previous_injuries_illnesses",
  CUR_MEDICATION = "current_medications",
  COMMENT_REQ = "comments_requests"
}

export enum FireFormKeys {
  FIRST_NAME = "firstName",
  LAST_NAME = "lastName",
  ADDRESS = "address",
  CITY = "city",
  STATE = "state",
  ZIPCODE = "zipCode",
  PROPERTY_TYPE = "propertyType",
  YEAR_BUILT = "yearBuilt",
  SQUARE_FEET = "squareFootage",
  NUM_STOREIS = "numStories",
  CONSTRUCTION_TYPE = "constructionType",
  WORKING_SMOKE_DECTORS = "workingSmokeDectors",
  FIRE_EXTINGUISHERS = "fireExtinguishers",
  SPRINKLE_SYSTEM = "sprinklerSystem",
  FIRE_ALARM_SYSTEM = "fireAlarmSystem",
  DISTANCE_TO_FIRESTATION = "distanceToFireStation",
  DISTANCE_TO_FIREHYDRANT = "distanceToFireHydrant",
  PREV_FIRE_LOSS = "previousFireLoss",
  PREV_FIRE_LOSS_DETAIL = "previousFireLossDetails"
}