import { AutomobileFormKeys, DisabilityFormKeys, FireFormKeys, LiabilityFormKeys, PetFormKeys, TermFormKeys } from "../../Pages/Insurance/Forms/formkeys"

type FormLabels = {
    [key: string]: string;
}


const TermFormLabels = {
    [TermFormKeys.NAME]: "Name",
    [TermFormKeys.AGE]: "Age",
    [TermFormKeys.GENDER]: "Gender",
    [TermFormKeys.HEALTH_CONDITION]: "Health Condition",
    [TermFormKeys.SMOKING]: "Smoking Condition",
    [TermFormKeys.ALCOHOLIC]: "Alcoholic Condition",
    [TermFormKeys.NOMINES]: "No of Nomines",
    [TermFormKeys.PROFESSION]: "Profession",
    [TermFormKeys.LPA]: "Annual Income",
    [TermFormKeys.CLAIM_AMT]: "Claim Amount",
    [TermFormKeys.PREMIUM_AMT]: "Premium Amount",
    [TermFormKeys.SUB_TYPE]: "Subscription Type",
    [TermFormKeys.POLICY_DURATION]: "Policy Duration",
}

const LiabilityFormLabels = {
    [LiabilityFormKeys.NAME]: "Name",
    [LiabilityFormKeys.ADDRESS]: "Address",
    [LiabilityFormKeys.LOCATION_TYPE]: "Location",
    [LiabilityFormKeys.MOBILE]: "Phone Number",
    [LiabilityFormKeys.BUSINESS_TYPE]: "Business Domain",
    [LiabilityFormKeys.BUSINESS_DESC]: "Business Description",
    [LiabilityFormKeys.SERVICES]: "Services",
    [LiabilityFormKeys.TARGET]: "Target Audience",
    [LiabilityFormKeys.CLAIM_HISTORY]: "Claim History",
    [LiabilityFormKeys.CLAIM_TYPE]: "Claim Type",
    [LiabilityFormKeys.CLAIM_AMT]: "Claim Amount",
    [LiabilityFormKeys.RISK_ASS]: "Risk Assessment",
    [LiabilityFormKeys.RESPONSE_PLAN]: "Response Plan",
    [LiabilityFormKeys.BUILDING_AGE]: "Building Age",
    [LiabilityFormKeys.CONSTRUCTION_MTRL]: "Construction Material",
    [LiabilityFormKeys.PROTECTION]: "Protection",
    [LiabilityFormKeys.CONTROL_MEASURES]: "Control Measures",
    [LiabilityFormKeys.BUILDING_TYPE]: "Building Type",
    [LiabilityFormKeys.POLICY_TYPE]: "Policy Type",
    [LiabilityFormKeys.POLICY_PERIOD]: "Policy Period",
    [LiabilityFormKeys.LIMIT]: "Limit",
    [LiabilityFormKeys.PROPERTY]: "Property",
    [LiabilityFormKeys.PROPERTY_VALUE]: "Property Value",
    [LiabilityFormKeys.LIABILITY_EXPOSURE]: "Liability Exposure",
    [LiabilityFormKeys.REVENUE]: "Revenue",
    [LiabilityFormKeys.ENV_CONCERN]: "Environmental Concern",
    [LiabilityFormKeys.REGULATORY_ISSUE]: "Regulatory Issue",
    [LiabilityFormKeys.SPECIFIC_RISK]: "Specific Risk",
}

const DisabilityFormLabels = {
    [DisabilityFormKeys.NAME]: "Name",
    [DisabilityFormKeys.ADDRESS]: "Address",
    [DisabilityFormKeys.DOB]: "DOB",
    [DisabilityFormKeys.AGE]: "Age",
    [DisabilityFormKeys.SECURITY_NUM]: "Security Number",
    [DisabilityFormKeys.JOB_TITLE]: "Job Title",
    [DisabilityFormKeys.COMPANY]: "Company",
    [DisabilityFormKeys.INDUSTRY]: "Industry",
    [DisabilityFormKeys.DURATION]: "Duration",
    [DisabilityFormKeys.JOB_DUTIES]: "Job Duties",
    [DisabilityFormKeys.ANNUAL_INCOME]: "Annual Income",
    [DisabilityFormKeys.EDUCATION]: "Education",
    [DisabilityFormKeys.CLG]: "College",
    [DisabilityFormKeys.PAST_ILLNESS]: "Past Illness",
    [DisabilityFormKeys.INJURIES]: "Injuries",
    [DisabilityFormKeys.CURRENT_HEALTH_STATUS]: "Current Health Status",
    [DisabilityFormKeys.FAM_ILLNESS_HISTORY]: "Family Illness History",
    [DisabilityFormKeys.CURRENT_TREATMENT]: "Current Treatment",
    [DisabilityFormKeys.DISABILITY_INFO]: "Disability Information",
    [DisabilityFormKeys.DISABILITY_DURATION]: "Disability Duration",
    [DisabilityFormKeys.DAILY_IMPACT]: "Daily Impact",
    [DisabilityFormKeys.DOCTOR_NAME]: "Doctor Name",
    [DisabilityFormKeys.DOCTOR_ADDRESS]: "Doctor Address",
    [DisabilityFormKeys.DOCTOR_CONTACT_INFO]: "Doctor Information",
    [DisabilityFormKeys.SERVICE_PERIOD]: "Service Period",
    [DisabilityFormKeys.INCOME]: "Income",
    [DisabilityFormKeys.OTHER_INCOME]: "Other Income",
    [DisabilityFormKeys.DEPENDENTS]: "Dependents",
    [DisabilityFormKeys.SPOUSE_NAME]: "Spouse Name",
    [DisabilityFormKeys.SPOUSE_AGE]: "Spouse Age",
    [DisabilityFormKeys.CHILDREN_CNT]: "Children Count",
    [DisabilityFormKeys.CHILDREN_NAME_AGE]: "Children Name and Age",
    [DisabilityFormKeys.MILITARY_SERVICE_DATE]: "Military Service Date",
    [DisabilityFormKeys.LIFE_INSURANCE]: "Life Insurance",
    [DisabilityFormKeys.HEALTH_INSURANCE]: "Health Insurance",
    [DisabilityFormKeys.LONG_TERM_CARE_INSURANCE]: "Long Term Insurance",
}

const AutomobileFormLabels = {
    [AutomobileFormKeys.NAME]: "Name",
    [AutomobileFormKeys.ADDRESS]: "Address",
    [AutomobileFormKeys.DOB]: "DOB",
    [AutomobileFormKeys.GENDER]: "Gender",
    [AutomobileFormKeys.PHONE]: "Phone",
    [AutomobileFormKeys.EMAIL]: "Email",
    [AutomobileFormKeys.VEHICLE_MAKE]: "Vehicle Make",
    [AutomobileFormKeys.VEHICLE_MODEL]: "vehicle Model",
    [AutomobileFormKeys.VEHICLE_YEAR]: "Vehicle Year",
    [AutomobileFormKeys.VIN]: "VIN",
    [AutomobileFormKeys.VEHICLE_CLASS]: "Vehicle Class",
    [AutomobileFormKeys.ENGINE_CAPACITY]: "Engine Capacity",
    [AutomobileFormKeys.FUEL_TYPE]: "Fuel Type",
    [AutomobileFormKeys.VEHICLE_VALUE]: "Vehicle Value",
    [AutomobileFormKeys.DRIVER_LICENSE_NUM]: "License Number",
    [AutomobileFormKeys.DRIVER_LINCENSE_CLASS]: "License Class",
    [AutomobileFormKeys.DRIVING_EXPERIENCE]: "Driving Experience",
    [AutomobileFormKeys.PREVIOUS_VIOLATION]: "Previous Violation",
    [AutomobileFormKeys.INSURANCE_TYPE]: "Insurance Type",
    [AutomobileFormKeys.POLICY_START]: "Policy Start",
    [AutomobileFormKeys.POLICY_END]: "Policy End",
    [AutomobileFormKeys.COVERAGE_LIMIT]: "Coverage Limit",
    [AutomobileFormKeys.DEDUCTIBLE_AMT]: "Deductible Amount",
    [AutomobileFormKeys.PREMIUM_AMT]: "Premium Amount",
    [AutomobileFormKeys.PAYMENT_FREQ]: "Payment Frequency",
    [AutomobileFormKeys.PAYMENT_METHOD]: "Payment Method",
    [AutomobileFormKeys.ADDITIONAL_DRIVER]: "Additional Driver",
    [AutomobileFormKeys.ADDITIONAL_FEATURE]: "Additional Feature"
}

const PetFormLabels = {
    [PetFormKeys.FULL_NAME]: "Full Name",
    [PetFormKeys.ADDRESS]: "Address",
    [PetFormKeys.CITY]: "City",
    [PetFormKeys.STATE]: "State",
    [PetFormKeys.ZIP_CODE]: "ZipCode",
    [PetFormKeys.PHONE_NO]: "Phone No",
    [PetFormKeys.EMAIL]: "Email",
    [PetFormKeys.PET_NAME]: "Pet Name",
    [PetFormKeys.SPECIES]: "Species",
    [PetFormKeys.BREED]: "Breed",
    [PetFormKeys.AGE]: "Age",
    [PetFormKeys.GENDER]: "Gender",
    [PetFormKeys.SPAYED_NEUTERED]: "Spayed Neutered",
    [PetFormKeys.MICROCHIPPED]: "Microchipped",
    [PetFormKeys.MICROCHIP_NO]: "Microchip No",
    [PetFormKeys.ACCIDENT_COVERAGE]: "Accident Coverage",
    [PetFormKeys.ILLNESS_COVERAGE]: "Illness Coverage",
    [PetFormKeys.ROUTINE_CARE]: "Routine Care",
    [PetFormKeys.OTHER]: "Other",
    [PetFormKeys.MEDICAL_CONDITION]: "Medical Condition",
    [PetFormKeys.PREV_INJURIES_ILLNESS]: "Previous Illness/injuries",
    [PetFormKeys.CUR_MEDICATION]: "Current Medication",
    [PetFormKeys.COMMENT_REQ]: "Comments Requests",
}

const FireFormLabels = {
    [FireFormKeys.FIRST_NAME]: "First Name",
    [FireFormKeys.LAST_NAME]: "Last Name",
    [FireFormKeys.ADDRESS]: "Address",
    [FireFormKeys.CITY]: "City",
    [FireFormKeys.STATE]: "State",
    [FireFormKeys.ZIPCODE]: "ZipCode",
    [FireFormKeys.PROPERTY_TYPE]: "Property Type",
    [FireFormKeys.YEAR_BUILT]: "Year Built",
    [FireFormKeys.SQUARE_FEET]: "Square Feet",
    [FireFormKeys.NUM_STOREIS]: "No Stories",
    [FireFormKeys.CONSTRUCTION_TYPE]: "Construction Type",
    [FireFormKeys.WORKING_SMOKE_DECTORS]: "Working Smoke Dectors",
    [FireFormKeys.FIRE_EXTINGUISHERS]: "Fire Extinguishers",
    [FireFormKeys.SPRINKLE_SYSTEM]: "Sprinkle System",
    [FireFormKeys.FIRE_ALARM_SYSTEM]: "Fire Alarm System",
    [FireFormKeys.DISTANCE_TO_FIRESTATION]: "Distance To FireStation",
    [FireFormKeys.DISTANCE_TO_FIREHYDRANT]: "Distance To FireHydrant",
    [FireFormKeys.PREV_FIRE_LOSS]: "Previous Fire Loss",
    [FireFormKeys.PREV_FIRE_LOSS_DETAIL]: "Previous Fire Loss Detail",
}

const formLabels: FormLabels = {
    ...TermFormLabels,
    ...LiabilityFormLabels,
    ...DisabilityFormLabels,
    ...AutomobileFormLabels, 
    ...PetFormLabels,
    ...FireFormLabels,
};

export default formLabels;